version: "3.8"
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - webnet
    depends_on:
      - mongo
      - api
    links:
      - api

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodb-data:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: username
    #   MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    networks:
      - webnet

  # mongo-express:
  #   container_name: mongo-express
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   networks:
  #     - webnet
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: username
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: password
  #     ME_CONFIG_BASICAUTH_UERNAME: username
  #     ME_CONFIG_BASICAUTH_PASSWORD: password
  #   depends_on:
  #     - mongo
  #   links:
  #     - mongo

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9876:9876"
    networks:
      - webnet
    environment:
      - MONGO_URI=mongodb://mongo:27017/cookbook
    depends_on:
      - mongo
    links:
      - mongo
  
networks:
  webnet:

volumes:
  mongodb-data:
