version: "3.8"
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - webnet
    depends_on:
      - api
    links:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9876:9876"
    networks:
      - webnet
    environment:
      - DEBUG=cookbook*
      # - MONGO_URI=fill in url here
  
networks:
  webnet:

volumes:
  mongodb-data:
